[package]
name = "wyj-store"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
wyj-config.workspace = true
wyj-core.workspace = true
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
tempfile.workspace = true
semver.workspace = true
sha2.workspace = true
flate2.workspace = true
tar.workspace = true
zip.workspace = true
uuid.workspace = true
cron.workspace = true
jsonschema.workspace = true
url.workspace = true

[dev-dependencies]
